institute = input("Enter the name of the Institute      ,")
name = input(" Enter the name of student        ,")
clas = input(" Enter the name  of class     ,")
roll_no  = input ("Enter the roll no of the student     ,")
enrollmnent_no = input("Enter the Enrollment Number     ,")
subj_1 = int(input("Enter the Marks of Physis"))
subj_1p = int(input("Enter the Marks of Physis Pratical"))
subj_2 = int(input("Enter the Marks of Math"))
subj_3 = int(input("Enter the Marks of Chemistry"))
subj_3p = int(input("Enter the Marks of Chemistry Pratical"))
subj_4 = int(input("Enter the Marks of english"))
subj_5 = int(input("Enter the Marks of Islamiat"))
marks_obt = (subj_1 + subj_1p + subj_2 + subj_3 + subj_3p + subj_4 + subj_5)
marks_total = 500
perc = float((marks_obt/500)*100)
print("#="*20)
print("Name = ", name)
print("Class = ", clas)
print("Roll no = ", roll_no)
print("|-----| ------------------|---------------|--------------------------")
print("|No   |       Subject     |       Marks   |       Marks obtain"       )
print("|-----| ------------------|---------------|--------------------------")
print("|1    |       Physis      |       75      |      =" ,subj_1           )
print("|2    |    Physis(pre)    |       25      |      =" ,subj_1p          )
print("|3    |        Math       |      100      |      =" ,subj_2           )
print("|4    |    Chemistry      |      75       |      =" ,subj_3           )
print("|5    |  Chemistry (pre ) |      25       |      =" ,subj_3p          )
print("|6    |       English     |      100      |      =" ,subj_4           )
print("|7    |      Islamiat     |      100      |      =" ,subj_5           )
print("|-----| ------------------|---------------|--------------------------")
print("|     |    Total Marks    |      500      |      =" ,marks_obt        )
print("|-----| ------------------|---------------|--------------------------")


print("#= " * 20)
print("Marks obtained =" ,marks_obt)
print("Total Marks  = ",marks_total)
print("Percentage = " , perc)
if (perc>=80):
    print("Grade = A+")
    print("Remarks = Excellent")
elif (perc>=70):
    print("Grade = A")
    print("Remarks = Very Good")
elif (perc>=60):
    print("Grade = B")
    print("Remarks = Good")
elif (perc>=50):
    print("Grade = C")
    print("Remarks = Have to Try Hard")
elif (perc<50):
    print("Grade = F")
    print("Remarks = Fail")